"""Build typed Python plugins for MiraBox Stream Dock.

The package-level namespace is the supported public API. It provides an action
runtime, immutable incoming-event and outgoing-command models, WebSocket
transport, typed JSON codecs, executable launch validation, logging, and the
version-matched Property Inspector browser client.

Typical applications register :class:`Action` subclasses in an
:class:`ActionRegistry`, build :class:`StreamDockApplication` with
:func:`create_stream_dock_application`, and pass the resulting factory to
:func:`run_plugin_cli`.

SDK logging is silent by default. Call :func:`configure_logging` explicitly when
transport or event-dispatch diagnostics are required.
"""

__version__ = "0.5.0"

from .action import Action
from .action_registry import (
    ActionClass,
    ActionRegistration,
    ActionRegistry,
    TypedActionRegistration,
)
from .cli import build_plugin_argument_parser, parse_plugin_cli_arguments, run_plugin_cli
from .codecs import (
    JSON_OBJECT_CODEC,
    FunctionalJsonCodec,
    JsonCodec,
    JsonObjectCodec,
    decode_with_codec,
    encode_with_codec,
)
from .commands import (
    GetGlobalSettingsCommand,
    GetSettingsCommand,
    LogMessageCommand,
    OpenUrlCommand,
    RegisterPluginCommand,
    SendToPropertyInspectorCommand,
    SetGlobalSettingsCommand,
    SetImageCommand,
    SetSettingsCommand,
    SetStateCommand,
    SetTitleCommand,
    ShowAlertCommand,
    ShowOkCommand,
    StreamDockCommand,
    ValidatedWireMessage,
)
from .completion import (
    CommandFuture,
    OutboundCommandBusClosedError,
    OutboundCommandBusError,
    OutboundCommandBusNotReadyError,
    OutboundQueueFullError,
)
from .diagnostics import SdkDiagnostic, SourceLocation
from .errors import (
    InvalidFieldError,
    InvalidPluginLaunchArgumentsError,
    InvalidRegistrationInfoError,
    JsonCodecDecodeError,
    JsonCodecEncodeError,
    JsonCodecError,
    MalformedEventError,
    StreamDockProtocolError,
    UnsupportedEventError,
)
from .events import (
    ActionEvent,
    ActionPayloadEvent,
    ApplicationDidLaunchEvent,
    ApplicationDidTerminateEvent,
    Controller,
    Coordinates,
    DeviceActionEvent,
    DeviceDidConnectEvent,
    DeviceDidDisconnectEvent,
    DeviceInfo,
    DeviceSize,
    DialDownEvent,
    DialPressEvent,
    DialRotateEvent,
    DialUpEvent,
    DidReceiveGlobalSettingsEvent,
    DidReceiveSettingsEvent,
    KeyDownEvent,
    KeyEvent,
    KeyUpEvent,
    PropertyInspectorDidAppearEvent,
    PropertyInspectorDidDisappearEvent,
    PropertyInspectorMessage,
    SendToPluginEvent,
    StreamDockEvent,
    StreamDockEventType,
    SystemDidWakeUpEvent,
    TitleAlignment,
    TitleParameters,
    TitleParametersDidChangeEvent,
    TouchTapEvent,
    UnknownStreamDockEvent,
    WillAppearEvent,
    WillDisappearEvent,
)
from .global_settings import GlobalSettings, GlobalSettingsBusyError
from .json_types import JsonObject, JsonValue, OwnedJsonPayload, ValidatedJsonObject
from .logging_config import LoggingOverflowPolicy, configure_logging, dropped_log_records
from .parser import parse_stream_dock_event
from .plugin_validation import validate_plugin
from .protocols import (
    PluginApplication,
    StreamDockActionDependencies,
    StreamDockSender,
)
from .registration import (
    PluginLaunchArguments,
    RegistrationApplicationInfo,
    RegistrationColors,
    RegistrationDeviceInfo,
    RegistrationInfo,
    RegistrationPluginInfo,
    parse_plugin_launch_arguments,
    parse_registration_info,
)
from .resources import (
    PROPERTY_INSPECTOR_CLIENT_FILENAME,
    copy_property_inspector_client,
    property_inspector_client_bytes,
)
from .runtime import (
    ActionContextMetrics,
    ApplicationContext,
    ApplicationRuntime,
    ApplicationService,
    ApplicationServiceFactory,
    CommandWriterMetrics,
    DependencyAwareActionRegistry,
    EventReaderMetrics,
    HandlerSchedulerMetrics,
    InboundEventQueueMetrics,
    InboundOverflowPolicy,
    OutboundCommandQueueMetrics,
    Plugin,
    PluginHooks,
    RuntimeDispatcherConfig,
    RuntimeEventPumpMetrics,
    RuntimeLifecycle,
    RuntimeRouterMetrics,
    RuntimeSchedulerKind,
    SessionCoordinatorMetrics,
    SessionReadiness,
    StreamDockApplication,
    StreamDockBoundaryMetrics,
    StreamDockQueueConfig,
    StreamDockRuntimeMetrics,
    StreamDockShutdownConfig,
    TransportQueueMetrics,
    WebSocketConnectorMetrics,
    create_stream_dock_application,
)
from .runtime.shutdown import ShutdownFailure, ShutdownOutcome, StopSignal

__all__ = [
    "SdkDiagnostic",
    "SourceLocation",
    "ShutdownFailure",
    "ShutdownOutcome",
    "StopSignal",
    "__version__",
    "Action",
    "ActionClass",
    "ActionContextMetrics",
    "ApplicationContext",
    "ApplicationRuntime",
    "ApplicationService",
    "ApplicationServiceFactory",
    "ActionRegistration",
    "ActionRegistry",
    "ActionEvent",
    "ActionPayloadEvent",
    "ApplicationDidLaunchEvent",
    "ApplicationDidTerminateEvent",
    "CommandFuture",
    "CommandWriterMetrics",
    "Controller",
    "Coordinates",
    "DeviceActionEvent",
    "DeviceDidConnectEvent",
    "DeviceDidDisconnectEvent",
    "DeviceInfo",
    "DeviceSize",
    "DialDownEvent",
    "DialPressEvent",
    "DialRotateEvent",
    "DialUpEvent",
    "DependencyAwareActionRegistry",
    "DidReceiveGlobalSettingsEvent",
    "DidReceiveSettingsEvent",
    "EventReaderMetrics",
    "GetGlobalSettingsCommand",
    "GetSettingsCommand",
    "GlobalSettings",
    "GlobalSettingsBusyError",
    "HandlerSchedulerMetrics",
    "FunctionalJsonCodec",
    "InvalidFieldError",
    "InvalidPluginLaunchArgumentsError",
    "InvalidRegistrationInfoError",
    "InboundEventQueueMetrics",
    "InboundOverflowPolicy",
    "JSON_OBJECT_CODEC",
    "JsonObject",
    "JsonObjectCodec",
    "JsonCodec",
    "JsonCodecDecodeError",
    "JsonCodecEncodeError",
    "JsonCodecError",
    "JsonValue",
    "KeyDownEvent",
    "KeyEvent",
    "KeyUpEvent",
    "LogMessageCommand",
    "LoggingOverflowPolicy",
    "MalformedEventError",
    "OpenUrlCommand",
    "OutboundCommandBusClosedError",
    "OutboundCommandBusError",
    "OutboundCommandBusNotReadyError",
    "OutboundCommandQueueMetrics",
    "OutboundQueueFullError",
    "OwnedJsonPayload",
    "PropertyInspectorDidAppearEvent",
    "PropertyInspectorDidDisappearEvent",
    "PropertyInspectorMessage",
    "PluginLaunchArguments",
    "PluginApplication",
    "Plugin",
    "PluginHooks",
    "PROPERTY_INSPECTOR_CLIENT_FILENAME",
    "RegisterPluginCommand",
    "RegistrationApplicationInfo",
    "RegistrationColors",
    "RegistrationDeviceInfo",
    "RegistrationInfo",
    "RegistrationPluginInfo",
    "SendToPluginEvent",
    "SendToPropertyInspectorCommand",
    "SetGlobalSettingsCommand",
    "SetImageCommand",
    "SetSettingsCommand",
    "SetStateCommand",
    "SetTitleCommand",
    "ShowAlertCommand",
    "ShowOkCommand",
    "StreamDockCommand",
    "StreamDockActionDependencies",
    "RuntimeDispatcherConfig",
    "RuntimeEventPumpMetrics",
    "RuntimeLifecycle",
    "RuntimeRouterMetrics",
    "RuntimeSchedulerKind",
    "SessionReadiness",
    "SessionCoordinatorMetrics",
    "StreamDockApplication",
    "StreamDockBoundaryMetrics",
    "StreamDockEvent",
    "StreamDockEventType",
    "StreamDockQueueConfig",
    "StreamDockProtocolError",
    "StreamDockSender",
    "StreamDockRuntimeMetrics",
    "StreamDockShutdownConfig",
    "SystemDidWakeUpEvent",
    "TitleAlignment",
    "TitleParameters",
    "TitleParametersDidChangeEvent",
    "TouchTapEvent",
    "TransportQueueMetrics",
    "TypedActionRegistration",
    "UnknownStreamDockEvent",
    "UnsupportedEventError",
    "ValidatedJsonObject",
    "ValidatedWireMessage",
    "WillAppearEvent",
    "WillDisappearEvent",
    "WebSocketConnectorMetrics",
    "build_plugin_argument_parser",
    "configure_logging",
    "copy_property_inspector_client",
    "create_stream_dock_application",
    "decode_with_codec",
    "dropped_log_records",
    "encode_with_codec",
    "parse_plugin_cli_arguments",
    "parse_plugin_launch_arguments",
    "parse_registration_info",
    "parse_stream_dock_event",
    "property_inspector_client_bytes",
    "validate_plugin",
    "run_plugin_cli",
]
