"""Public API for the typed MiraBox Stream Dock SDK."""

__version__ = "0.1.2"

from .action import Action
from .action_registry import ActionRegistry
from .cli import build_plugin_argument_parser, parse_plugin_cli_arguments, run_plugin_cli
from .codecs import (
    JSON_OBJECT_CODEC,
    FunctionalJsonCodec,
    JsonCodec,
    JsonObjectCodec,
    decode_with_codec,
    encode_with_codec,
)
from .commands import (
    GetGlobalSettingsCommand,
    GetSettingsCommand,
    LogMessageCommand,
    OpenUrlCommand,
    RegisterPluginCommand,
    SendToPropertyInspectorCommand,
    SetGlobalSettingsCommand,
    SetImageCommand,
    SetSettingsCommand,
    SetStateCommand,
    SetTitleCommand,
    ShowAlertCommand,
    ShowOkCommand,
    StreamDockCommand,
)
from .connection import WebSocketStreamDockConnection
from .errors import (
    InvalidFieldError,
    InvalidPluginLaunchArgumentsError,
    InvalidRegistrationInfoError,
    JsonCodecDecodeError,
    JsonCodecEncodeError,
    JsonCodecError,
    MalformedEventError,
    StreamDockProtocolError,
    UnsupportedEventError,
)
from .events import (
    ActionEvent,
    ActionPayloadEvent,
    ApplicationDidLaunchEvent,
    ApplicationDidTerminateEvent,
    Controller,
    Coordinates,
    DeviceActionEvent,
    DeviceDidConnectEvent,
    DeviceDidDisconnectEvent,
    DeviceInfo,
    DeviceSize,
    DialDownEvent,
    DialPressEvent,
    DialRotateEvent,
    DialUpEvent,
    DidReceiveGlobalSettingsEvent,
    DidReceiveSettingsEvent,
    KeyDownEvent,
    KeyEvent,
    KeyUpEvent,
    PropertyInspectorDidAppearEvent,
    PropertyInspectorDidDisappearEvent,
    PropertyInspectorMessage,
    SendToPluginEvent,
    StreamDockEvent,
    StreamDockEventType,
    SystemDidWakeUpEvent,
    TitleAlignment,
    TitleParameters,
    TitleParametersDidChangeEvent,
    TouchTapEvent,
    UnknownStreamDockEvent,
    WillAppearEvent,
    WillDisappearEvent,
)
from .json_types import JsonObject, JsonValue
from .parser import parse_stream_dock_event
from .plugin import StreamDockPlugin
from .protocols import (
    LifecycleService,
    PluginApplication,
    StreamDockActionDependencies,
    StreamDockConnection,
    StreamDockListener,
    StreamDockSender,
)
from .registration import (
    PluginLaunchArguments,
    RegistrationApplicationInfo,
    RegistrationColors,
    RegistrationDeviceInfo,
    RegistrationInfo,
    RegistrationPluginInfo,
    parse_plugin_launch_arguments,
    parse_registration_info,
)
from .resources import (
    PROPERTY_INSPECTOR_CLIENT_FILENAME,
    copy_property_inspector_client,
    property_inspector_client_bytes,
)

__all__ = [
    "__version__",
    "Action",
    "ActionRegistry",
    "ActionEvent",
    "ActionPayloadEvent",
    "ApplicationDidLaunchEvent",
    "ApplicationDidTerminateEvent",
    "Controller",
    "Coordinates",
    "DeviceActionEvent",
    "DeviceDidConnectEvent",
    "DeviceDidDisconnectEvent",
    "DeviceInfo",
    "DeviceSize",
    "DialDownEvent",
    "DialPressEvent",
    "DialRotateEvent",
    "DialUpEvent",
    "DidReceiveGlobalSettingsEvent",
    "DidReceiveSettingsEvent",
    "GetGlobalSettingsCommand",
    "GetSettingsCommand",
    "FunctionalJsonCodec",
    "InvalidFieldError",
    "InvalidPluginLaunchArgumentsError",
    "InvalidRegistrationInfoError",
    "JSON_OBJECT_CODEC",
    "JsonObject",
    "JsonObjectCodec",
    "JsonCodec",
    "JsonCodecDecodeError",
    "JsonCodecEncodeError",
    "JsonCodecError",
    "JsonValue",
    "KeyDownEvent",
    "KeyEvent",
    "KeyUpEvent",
    "LifecycleService",
    "LogMessageCommand",
    "MalformedEventError",
    "OpenUrlCommand",
    "PropertyInspectorDidAppearEvent",
    "PropertyInspectorDidDisappearEvent",
    "PropertyInspectorMessage",
    "PluginLaunchArguments",
    "PluginApplication",
    "PROPERTY_INSPECTOR_CLIENT_FILENAME",
    "RegisterPluginCommand",
    "RegistrationApplicationInfo",
    "RegistrationColors",
    "RegistrationDeviceInfo",
    "RegistrationInfo",
    "RegistrationPluginInfo",
    "SendToPluginEvent",
    "SendToPropertyInspectorCommand",
    "SetGlobalSettingsCommand",
    "SetImageCommand",
    "SetSettingsCommand",
    "SetStateCommand",
    "SetTitleCommand",
    "ShowAlertCommand",
    "ShowOkCommand",
    "StreamDockCommand",
    "StreamDockActionDependencies",
    "StreamDockConnection",
    "StreamDockEvent",
    "StreamDockEventType",
    "StreamDockListener",
    "StreamDockPlugin",
    "StreamDockProtocolError",
    "StreamDockSender",
    "SystemDidWakeUpEvent",
    "TitleAlignment",
    "TitleParameters",
    "TitleParametersDidChangeEvent",
    "TouchTapEvent",
    "UnknownStreamDockEvent",
    "UnsupportedEventError",
    "WebSocketStreamDockConnection",
    "WillAppearEvent",
    "WillDisappearEvent",
    "build_plugin_argument_parser",
    "copy_property_inspector_client",
    "decode_with_codec",
    "encode_with_codec",
    "parse_plugin_cli_arguments",
    "parse_plugin_launch_arguments",
    "parse_registration_info",
    "parse_stream_dock_event",
    "property_inspector_client_bytes",
    "run_plugin_cli",
]
