"""Public JSON uses native containers; copy-on-write views stay inside the SDK."""

from typing import TypeAlias, TypeGuard

JsonValue: TypeAlias = None | bool | int | float | str | list[JsonValue] | dict[str, JsonValue]
JsonObject: TypeAlias = dict[str, JsonValue]

def clone_json_object(value: object) -> JsonObject: ...
def is_json_value(value: object) -> TypeGuard[JsonValue]: ...

class ValidatedJsonObject:
    def __init__(self, value: object) -> None: ...
    def owned_payload(self) -> OwnedJsonPayload: ...
    def isolated_copy(self) -> JsonObject: ...
    def _copy_on_write_view(self) -> JsonObject: ...

class OwnedJsonPayload(dict[str, JsonValue]):
    def __init__(self, value: object | ValidatedJsonObject) -> None: ...
    def isolated_copy(self) -> JsonObject: ...
    def __copy__(self) -> JsonObject: ...
    def __deepcopy__(self, memo: dict[int, object]) -> JsonObject: ...
    def _validated_object(self) -> ValidatedJsonObject: ...

_CopyOnWriteJsonSource = ValidatedJsonObject

def _clone_json_object_source(value: object) -> _CopyOnWriteJsonSource: ...
